### ISSUE TITLE
请教一下接口异常的原因

### ISSUE THREAD

**Issue by CMHopeSunshine** [GardenHamster/GenshinPray#5]
调用接口返回的JSON：
{'code': 500, 'message': '接口异常', 'data': None}
日志：
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
2021-12-17 18:47:37,980 [10] ERROR ConsoleLog - Parameter is not valid.
param：authorzation：myguild，memberCode：'1'，toBase64：False，imgWidth：0
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(String filename, Boolean useIcm)
   at System.Drawing.Bitmap..ctor(String filename)
   at GenshinPray.Util.DrawHelper.drawOnePrayImg(YSPrayRecord YSPrayRecord, Int32 imgWidth) in D:\project\GenshinPray\GenshinPray\Util\DrawHelper.cs:line 57
   at GenshinPray.Service.PrayService.BasePrayService.DrawPrayImg(YSPrayRecord[] sortPrayRecords, Int32 imgWidth) in D:\project\GenshinPray\GenshinPray\Service\PrayService\BasePrayService.cs:line 203
   at GenshinPray.Service.PrayService.RolePrayService.GetPrayResult(MemberPO memberInfo, YSUpItem ysUpItem, Int32 prayCount, Int32 imgWidth) in D:\project\GenshinPray\GenshinPray\Service\PrayService\RolePrayService.cs:line 136
   at GenshinPray.Controllers.Api.RolePrayController.PrayOne(String memberCode, Boolean toBase64, Int32 imgWidth) in D:\project\GenshinPray\GenshinPray\Controllers\Api\RolePrayController.cs:line 43

**Comment by CMHopeSunshine** [comment]
没事了，是我资源路径搞错了...不过图片中文字符显示不出来
